spring.application.name=plcweb

# --- XÓA DÒNG "spring.autoconfigure.exclude..." ĐI NHÉ ---

server.port=8081
server.address=0.0.0.0

# --- KẾT NỐI MYSQL ---
spring.datasource.url=jdbc:mysql://localhost:3306/lathe_machine?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

# Cấu hình tự động
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true